nums = {1, 3, 5, 7, 9, 11}
print("Conjunto 'nums' original: ",nums,"\n")
print("Comprobamos si 6 si existe en nums:")
print(6 in nums)
print("Comprobamos si 7 si existe en nums:")
print(7 in nums)
print("Comprobamos si 11 si existe en nums:")
print(11 in nums)
print("Comprobamos si 0 si existe en nums:")
print(0 in nums)
print("\nComprobamos si 6 si NO existe en nums")
print(6 not in nums)
print("Comprobamos si 7 si NO existe en nums")
print(7 not in nums)
print("Comprobamos si 11 si NO existe en nums")
print(11 not in nums)
print("Comprobamos si 0 si NO existe en nums")
print(0 not in nums)